### ISSUE TITLE
Azure files support

### ISSUE THREAD

**Issue by drakkan** [hirochachacha/go-smb2#44]
Hi, 

I just did a quick test using the [file manipulation example](https://github.com/hirochachacha/go-smb2#file-manipulation) and Azure files as backend, the example crashes with the following error while trying to mount the share:

```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x55f565]

goroutine 1 [running]:
github.com/hirochachacha/go-smb2.(*session).encrypt(0xc00018a000, 0xc000130000, 0x44, 0x44, 0x7fab3459a800, 0x7fab34790fff, 0xc0000eb698, 0x41a2de, 0x7fab3459a700)
	/home/nicola/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.0.9/session.go:343 +0x45
github.com/hirochachacha/go-smb2.(*conn).makeRequestResponse(0xc00009f040, 0x6012a8, 0xc00012e000, 0x0, 0x601630, 0xc0000a2000, 0x713be8, 0x713be8, 0x203000)
	/home/nicola/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.0.9/conn.go:449 +0x2d1
github.com/hirochachacha/go-smb2.(*conn).sendWith(0xc00009f040, 0x6012a8, 0xc00012e000, 0x0, 0x601630, 0xc0000a2000, 0x0, 0x0, 0x0)
	/home/nicola/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.0.9/conn.go:384 +0x20a
github.com/hirochachacha/go-smb2.(*conn).send(...)
	/home/nicola/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.0.9/conn.go:366
github.com/hirochachacha/go-smb2.(*session).sendRecv(0xc00018a000, 0xc000120002, 0x6012a8, 0xc00012e000, 0x601630, 0xc0000a2000, 0x7fab34790fff, 0xc0000eb8b8, 0x41a2de, 0x7fab3459a600, ...)
	/home/nicola/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.0.9/session.go:284 +0x66
github.com/hirochachacha/go-smb2.(*session).logoff(0xc00018a000, 0x601630, 0xc0000a2000, 0x0, 0xc0001260a0)
	/home/nicola/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.0.9/session.go:272 +0x75
github.com/hirochachacha/go-smb2.(*Session).Logoff(0xc000120000, 0x0, 0x0)
	/home/nicola/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.0.9/client.go:92 +0x45
panic(0x57ed00, 0x6da3f0)
	/usr/lib/go/src/runtime/panic.go:965 +0x1b9
github.com/hirochachacha/go-smb2.(*session).encrypt(0xc00018a000, 0xc000128000, 0xac, 0xac, 0xc0000ebc10, 0x419e93, 0x7fab32c30b98, 0x0, 0x601c78)
	/home/nicola/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.0.9/session.go:343 +0x45
github.com/hirochachacha/go-smb2.(*conn).makeRequestResponse(0xc00009f040, 0x601398, 0xc000126000, 0x0, 0x601630, 0xc0000a2000, 0x0, 0x0, 0x7fab32c30b98)
	/home/nicola/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.0.9/conn.go:449 +0x2d1
github.com/hirochachacha/go-smb2.(*conn).sendWith(0xc00009f040, 0x601398, 0xc000126000, 0x0, 0x601630, 0xc0000a2000, 0x0, 0x0, 0x0)
	/home/nicola/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.0.9/conn.go:384 +0x20a
github.com/hirochachacha/go-smb2.(*conn).send(...)
	/home/nicola/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.0.9/conn.go:366
github.com/hirochachacha/go-smb2.treeConnect(0xc00018a000, 0x5b7ce7, 0x32, 0x0, 0x601630, 0xc0000a2000, 0xc0000a2000, 0xc00018a000, 0x0)
	/home/nicola/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.0.9/tree_conn.go:29 +0xae
github.com/hirochachacha/go-smb2.(*Session).Mount(0xc000120000, 0x5b7ce7, 0x32, 0x602220, 0xc0000b6040, 0xc000120000)
	/home/nicola/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.0.9/client.go:110 +0x10d
main.main()
	/home/nicola/goprojects/smb/main.go:32 +0x1f1
```

is Azure files supported/tested? Do I have to change some parameters to make it work? 

Thank you

**Comment by hirochachacha** [comment]
Thanks for the report. I think it works now.

**Comment by drakkan** [comment]
It works now, thank you for the quick fix.
